# Copyright 2026 Shohruh Miryusupov
# SPDX-License-Identifier: Apache-2.0

"""Finite-dimensional Nehari/AAK helper routines.

These helpers sit above the C++ finite Hankel primitives.  They are intended as
small, inspectable building blocks for tutorials and experiments, not as a
claim of full infinite-dimensional Nehari or Adamyan--Arov--Krein optimality.

The main workflow is:

1. approximate an anticausal tail with ``finite_nehari_approximate_tail``;
2. fit a scalar recurrence to the Hankelized tail;
3. select the first rank that satisfies user-chosen error and stability limits.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any
from collections.abc import Iterable

import numpy as np

from ._core import (
    denominator_to_reflection,
    finite_nehari_approximate_tail,
    iir_impulse_response,
    reflection_to_denominator,
)


@dataclass(frozen=True)
class FiniteNehariCandidateCriteria:
    """Selection thresholds for finite Nehari/rational SISO candidates.

    Parameters
    ----------
    max_tail_error:
        Maximum relative error between the original anticausal tail and the
        Hankelized finite Nehari approximation.
    max_rational_error:
        Maximum relative error between the original tail and the fitted rational
        recurrence realization.
    max_pole_radius:
        Maximum allowed modulus of the fitted recurrence poles.  Values below
        one indicate a stable causal realization of the fitted tail model.
    """

    max_tail_error: float = 1e-3
    max_rational_error: float = 1e-2
    max_pole_radius: float = 0.99

    def __post_init__(self) -> None:
        for name, value in (
            ("max_tail_error", self.max_tail_error),
            ("max_rational_error", self.max_rational_error),
            ("max_pole_radius", self.max_pole_radius),
        ):
            if not np.isfinite(float(value)) or float(value) < 0.0:
                raise ValueError(f"{name} must be finite and non-negative")


def _as_1d_float(name: str, value: Any) -> np.ndarray:
    array = np.asarray(value, dtype=np.float64)
    if array.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")
    if array.size == 0:
        raise ValueError(f"{name} must not be empty")
    if not np.all(np.isfinite(array)):
        raise ValueError(f"{name} must contain only finite values")
    return np.ascontiguousarray(array)


def finite_hankel_matrix_from_tail(tail: Any, *, rows: int, cols: int) -> np.ndarray:
    """Return the finite Hankel matrix generated by an anticausal tail.

    ``tail[n]`` is placed on anti-diagonals so that ``H[i, j] = tail[i + j]``.
    This is the finite-section object used by the Nehari/AAK teaching helpers.
    """

    tail_arr = _as_1d_float("tail", tail)
    rows_i = int(rows)
    cols_i = int(cols)
    if rows_i <= 0 or cols_i <= 0:
        raise ValueError("rows and cols must be positive")
    need = rows_i + cols_i - 1
    if tail_arr.size < need:
        raise ValueError("tail is too short for requested finite Hankel dimensions")
    return np.asarray(
        [[tail_arr[i + j] for j in range(cols_i)] for i in range(rows_i)], dtype=np.float64
    )


def finite_aak_siso_certificate(
    tail: Any,
    *,
    rank: int,
    rows: int,
    cols: int,
    criteria: FiniteNehariCandidateCriteria | None = None,
) -> dict[str, Any]:
    """Build a finite-section SISO AAK/Nehari diagnostic certificate.

    This routine is the first "true AAK/Nehari" bridge in the package: it
    uses the Schmidt-pair equations for the finite Hankel matrix directly.
    For a chosen target rank ``r``, it reports the first neglected singular
    value ``sigma_next``, verifies the finite Schmidt-pair identities

    ``H v = sigma_next u`` and ``H.T u = sigma_next v``,

    and attaches the existing finite Nehari/rational candidate for the same
    rank.  It is still a finite-section diagnostic, not a full infinite
    Hardy-space AAK/Nehari solver.
    """

    tail_arr = _as_1d_float("tail", tail)
    rank_i = int(rank)
    if rank_i < 0:
        raise ValueError("rank must be non-negative")

    hankel = finite_hankel_matrix_from_tail(tail_arr, rows=rows, cols=cols)
    u, singular_values, vt = np.linalg.svd(hankel, full_matrices=False)
    max_rank = singular_values.size
    if rank_i >= max_rank:
        raise ValueError("rank must be smaller than min(rows, cols) so sigma_next exists")

    if rank_i == 0:
        rank_approx = np.zeros_like(hankel)
    else:
        rank_approx = (u[:, :rank_i] * singular_values[:rank_i]) @ vt[:rank_i, :]

    residual_matrix = hankel - rank_approx
    rank_svd_error = float(np.linalg.norm(residual_matrix, ord=2))

    sigma_next = float(singular_values[rank_i])
    left = np.asarray(u[:, rank_i], dtype=np.float64)
    right = np.asarray(vt[rank_i, :], dtype=np.float64)
    left_residual = float(np.linalg.norm(hankel @ right - sigma_next * left))
    right_residual = float(np.linalg.norm(hankel.T @ left - sigma_next * right))

    candidate = finite_nehari_rational_candidates(
        tail_arr,
        ranks=[rank_i],
        rows=int(rows),
        cols=int(cols),
        criteria=criteria or FiniteNehariCandidateCriteria(),
    )[0]

    return {
        "method": "finite_section_siso_aak_nehari_certificate",
        "rank": rank_i,
        "rows": int(rows),
        "cols": int(cols),
        "hankel_singular_values": singular_values,
        "sigma_next": sigma_next,
        "rank_svd_error": rank_svd_error,
        "schmidt_left_residual": left_residual,
        "schmidt_right_residual": right_residual,
        "left_schmidt_vector": left,
        "right_schmidt_vector": right,
        "finite_hankel_matrix": hankel,
        "rank_svd_approximation": rank_approx,
        "candidate": candidate,
        "accepted": bool(candidate["accepted"]),
        "note": (
            "Finite-section Schmidt-pair AAK/Nehari diagnostic. "
            "This certifies finite Hankel identities and candidate quality; "
            "it is scoped to finite-section diagnostics, not full infinite-dimensional AAK/Nehari solving."
        ),
    }


def relative_error(reference: Any, estimate: Any) -> float:
    """Return ``||reference - estimate||_2 / ||reference||_2``.

    The result is ``0`` when both arrays are zero.  A ``ValueError`` is raised
    when the shapes differ.
    """

    ref = np.asarray(reference, dtype=np.float64)
    est = np.asarray(estimate, dtype=np.float64)
    if ref.shape != est.shape:
        raise ValueError("reference and estimate must have the same shape")
    numerator = float(np.linalg.norm(ref - est))
    denominator = float(np.linalg.norm(ref))
    return numerator / denominator if denominator else numerator


def fit_rational_tail(tail: Any, order: int) -> dict[str, np.ndarray]:
    """Fit a scalar recurrence/IIR model to a tail sequence.

    For a sequence ``g[n]`` generated by a stable rational model, there are
    coefficients ``a_1, ..., a_p`` such that

    ``g[n] + a_1 g[n-1] + ... + a_p g[n-p] ≈ 0``.

    This routine estimates the recurrence by least squares and returns a scalar
    IIR denominator, numerator, and poles.  It is a practical finite-data
    rational bridge, not a standalone AAK solver.
    """

    tail_arr = _as_1d_float("tail", tail)
    order_i = int(order)
    if order_i < 0:
        raise ValueError("order must be non-negative")
    if order_i == 0:
        return {
            "denominator": np.array([1.0], dtype=np.float64),
            "numerator": np.array([float(tail_arr[0])], dtype=np.float64),
            "poles": np.empty(0, dtype=np.complex128),
        }
    if tail_arr.size < 2 * order_i + 1:
        raise ValueError("tail is too short for the requested rational order")

    design = []
    target = []
    for n in range(order_i, tail_arr.size):
        design.append([tail_arr[n - lag] for lag in range(1, order_i + 1)])
        target.append(-tail_arr[n])
    design_arr = np.asarray(design, dtype=np.float64)
    target_arr = np.asarray(target, dtype=np.float64)
    coeff, *_ = np.linalg.lstsq(design_arr, target_arr, rcond=None)
    denominator = np.concatenate(([1.0], coeff)).astype(np.float64, copy=False)

    numerator = np.zeros(order_i + 1, dtype=np.float64)
    for i in range(order_i + 1):
        numerator[i] = sum(float(denominator[j]) * float(tail_arr[i - j]) for j in range(i + 1))

    return {
        "denominator": denominator,
        "numerator": numerator,
        "poles": np.roots(denominator).astype(np.complex128, copy=False),
    }


def rational_tail_response(denominator: Any, numerator: Any, n_terms: int) -> np.ndarray:
    """Generate a scalar IIR impulse/tail sequence from coefficients."""

    denominator_arr = _as_1d_float("denominator", denominator)
    numerator_arr = _as_1d_float("numerator", numerator)
    n_terms_i = int(n_terms)
    if n_terms_i < 0:
        raise ValueError("n_terms must be non-negative")
    if abs(float(denominator_arr[0])) < 1e-15:
        raise ValueError("denominator[0] must be non-zero")

    a = denominator_arr / denominator_arr[0]
    b = numerator_arr / denominator_arr[0]
    y = np.zeros(n_terms_i, dtype=np.float64)
    for n in range(n_terms_i):
        value = float(b[n]) if n < b.size else 0.0
        for k in range(1, a.size):
            if n >= k:
                value -= float(a[k]) * float(y[n - k])
        y[n] = value
    return y


def finite_nehari_rational_candidates(
    tail: Any,
    *,
    ranks: Iterable[int],
    rows: int,
    cols: int,
    criteria: FiniteNehariCandidateCriteria | None = None,
) -> list[dict[str, Any]]:
    """Evaluate finite Nehari/rational candidates for multiple ranks.

    Each row contains the finite Nehari diagnostics, fitted rational model, pole
    stability diagnostic, and an ``accepted`` flag.  The first accepted row can
    be selected with :func:`select_finite_nehari_candidate`.
    """

    tail_arr = _as_1d_float("tail", tail)
    criteria = criteria or FiniteNehariCandidateCriteria()
    rank_list = [int(rank) for rank in ranks]
    if not rank_list:
        raise ValueError("ranks must contain at least one value")
    if any(rank < 0 for rank in rank_list):
        raise ValueError("ranks must be non-negative")

    output: list[dict[str, Any]] = []
    for rank in rank_list:
        nehari = finite_nehari_approximate_tail(
            tail_arr.tolist(), rank=rank, rows=int(rows), cols=int(cols)
        )
        approx_tail = np.asarray(nehari["approximated_tail"], dtype=np.float64)
        fit = fit_rational_tail(approx_tail, rank)
        rational = rational_tail_response(fit["denominator"], fit["numerator"], approx_tail.size)
        comparison_tail = tail_arr[: approx_tail.size]

        poles = np.asarray(fit["poles"], dtype=np.complex128)
        pole_radius = float(np.max(np.abs(poles))) if poles.size else 0.0
        tail_error = float(nehari["relative_tail_error"])
        rational_error = relative_error(comparison_tail, rational)
        rational_vs_hankelized = relative_error(approx_tail, rational)
        accepted = (
            tail_error <= criteria.max_tail_error
            and rational_error <= criteria.max_rational_error
            and pole_radius <= criteria.max_pole_radius
        )

        output.append(
            {
                "rank": rank,
                "sigma_next": float(nehari["sigma_next"]),
                "hankelized_tail_error": tail_error,
                "rational_error": rational_error,
                "rational_vs_hankelized_error": rational_vs_hankelized,
                "max_pole_radius": pole_radius,
                "accepted": bool(accepted),
                "approximated_tail": approx_tail,
                "rational_tail": rational,
                "denominator": np.asarray(fit["denominator"], dtype=np.float64),
                "numerator": np.asarray(fit["numerator"], dtype=np.float64),
                "poles": poles,
                "hankel_singular_values": np.asarray(
                    nehari["hankel_singular_values"], dtype=np.float64
                ),
                "finite_nehari": nehari,
            }
        )

    return output


def finite_aak_reduce_tail(
    tail: Any,
    *,
    ranks: Iterable[int],
    rows: int,
    cols: int,
    criteria: FiniteNehariCandidateCriteria | None = None,
    attach_certificate: bool = True,
) -> dict[str, Any]:
    """Select a finite-section SISO AAK/Nehari rational reduction candidate.

    This is the highest-level finite-section helper in the current package.  It
    evaluates several finite Nehari/rational candidates, selects the first one
    that satisfies the supplied accuracy and pole-radius criteria, and
    optionally attaches a finite Schmidt-pair certificate for the selected rank.

    The routine is intentionally named ``finite_aak_*`` rather than
    ``aak_reduce_iir``.  It is a finite-section SISO diagnostic/reduction
    workflow built from Hankel matrices, Schmidt-pair checks, and rational
    recurrence fitting.  It is not a full infinite-dimensional Hardy-space
    AAK/Nehari solver.
    """

    tail_arr = _as_1d_float("tail", tail)
    criteria = criteria or FiniteNehariCandidateCriteria()
    candidate_rows = finite_nehari_rational_candidates(
        tail_arr,
        ranks=ranks,
        rows=int(rows),
        cols=int(cols),
        criteria=criteria,
    )
    selected = select_finite_nehari_candidate(candidate_rows)
    selected_rank = int(selected["rank"])

    certificate = None
    if attach_certificate:
        certificate = finite_aak_siso_certificate(
            tail_arr,
            rank=selected_rank,
            rows=int(rows),
            cols=int(cols),
            criteria=criteria,
        )

    return {
        "method": "finite_section_siso_aak_nehari_reduction_candidate",
        "rows": int(rows),
        "cols": int(cols),
        "tail_length": int(tail_arr.size),
        "criteria": {
            "max_tail_error": float(criteria.max_tail_error),
            "max_rational_error": float(criteria.max_rational_error),
            "max_pole_radius": float(criteria.max_pole_radius),
        },
        "candidates": candidate_rows,
        "selected_rank": selected_rank,
        "selected": selected,
        "certificate": certificate,
        "accepted": bool(selected.get("accepted", False)),
        "note": (
            "Finite-section SISO AAK/Nehari reduction candidate. "
            "The selected model is a finite Hankel/rational approximation with "
            "diagnostic certificates; it is not a full infinite-dimensional solver."
        ),
    }


def finite_aak_reduce_iir(
    reflection: Any,
    numerator: Any,
    *,
    ranks: Iterable[int],
    n_impulse: int,
    rows: int,
    cols: int,
    criteria: FiniteNehariCandidateCriteria | None = None,
    attach_certificate: bool = True,
) -> dict[str, Any]:
    """Reduce a stable SISO lattice/IIR model with the finite AAK workflow.

    This helper applies :func:`finite_aak_reduce_tail` to the causal impulse
    response of a stable SISO lattice/IIR model.  The selected rational tail
    model is returned as numerator/denominator coefficients and, when stable in
    scalar lattice coordinates, as reflection coefficients.

    Parameters
    ----------
    reflection:
        Reflection/PARCOR coefficients of the full stable SISO denominator.
    numerator:
        Numerator coefficients of the full SISO IIR model.
    ranks:
        Candidate rational orders to evaluate.
    n_impulse:
        Number of impulse-response samples used for the finite-section problem.
    rows, cols:
        Finite Hankel dimensions.  The impulse response must contain at least
        ``rows + cols - 1`` samples.
    criteria:
        Candidate acceptance thresholds.  If omitted, conservative defaults are
        used.
    attach_certificate:
        Whether to attach a finite Schmidt-pair certificate for the selected
        rank.

    Notes
    -----
    This routine is still finite-section and diagnostic.  It is useful for
    stable SISO IIR experiments, but it is not a full infinite-dimensional
    AAK/Nehari solver.
    """

    reflection_arr = _as_1d_float("reflection", reflection)
    numerator_arr = _as_1d_float("numerator", numerator)
    n_impulse_i = int(n_impulse)
    if n_impulse_i <= 0:
        raise ValueError("n_impulse must be positive")
    if n_impulse_i < int(rows) + int(cols) - 1:
        raise ValueError("n_impulse must be at least rows + cols - 1")

    full_denominator = np.asarray(
        reflection_to_denominator(reflection_arr.tolist()), dtype=np.float64
    )
    full_impulse = np.asarray(
        iir_impulse_response(full_denominator.tolist(), numerator_arr.tolist(), n_impulse_i),
        dtype=np.float64,
    )

    tail_reduction = finite_aak_reduce_tail(
        full_impulse,
        ranks=ranks,
        rows=int(rows),
        cols=int(cols),
        criteria=criteria,
        attach_certificate=attach_certificate,
    )
    selected = tail_reduction["selected"]
    reduced_denominator = np.asarray(selected["denominator"], dtype=np.float64)
    reduced_numerator = np.asarray(selected["numerator"], dtype=np.float64)
    reduced_impulse = rational_tail_response(reduced_denominator, reduced_numerator, n_impulse_i)

    try:
        reduced_reflection = np.asarray(
            denominator_to_reflection(reduced_denominator.tolist()), dtype=np.float64
        )
        stable = True
    except ValueError:
        reduced_reflection = np.empty(0, dtype=np.float64)
        stable = False

    return {
        "method": "finite_section_siso_aak_nehari_iir_reduction_candidate",
        "full_reflection": reflection_arr,
        "full_denominator": full_denominator,
        "full_numerator": numerator_arr,
        "full_impulse_response": full_impulse,
        "reduced_reflection": reduced_reflection,
        "reduced_denominator": reduced_denominator,
        "reduced_numerator": reduced_numerator,
        "reduced_impulse_response": reduced_impulse,
        "stable": bool(stable),
        "relative_impulse_error": relative_error(full_impulse, reduced_impulse),
        "selected_rank": int(tail_reduction["selected_rank"]),
        "selected": selected,
        "candidates": tail_reduction["candidates"],
        "certificate": tail_reduction["certificate"],
        "accepted": bool(tail_reduction["accepted"] and stable),
        "tail_reduction": tail_reduction,
        "note": (
            "Finite-section SISO AAK/Nehari IIR reduction candidate. "
            "The model is selected from impulse-response data and converted back "
            "to scalar lattice coordinates when stable."
        ),
    }


def select_finite_nehari_candidate(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Return the first accepted candidate, or the lowest-rational-error row."""

    if not rows:
        raise ValueError("rows must not be empty")
    for row in rows:
        if bool(row.get("accepted", False)):
            return row
    return min(rows, key=lambda row: float(row["rational_error"]))
