"""Tutorial: from a finite Nehari tail to a rational SISO model.

This tutorial bridges the finite Nehari/AAK toy example to a practical
rational-model workflow.  The finite Nehari helper returns a Hankelized
approximation of an anticausal tail.  Here we ask a practical question: can
that approximated tail be represented by a small recursive/rational model?

The answer is yes for the synthetic low-rank tail used here.  We fit a short
linear recurrence to the Hankelized tail, convert that recurrence to a causal
IIR impulse response, and compare the original tail, the finite Nehari tail, and
the rational realization.

This is still not an exact infinite-dimensional AAK/Nehari solver.  It is a
small numerical bridge from Hankel singular values to rational filters.
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

import numpy as np


def artifact_dir() -> Path:
    path = Path(os.environ.get("LATTICE_DSP_ARTIFACT_DIR", "reports/example-artifacts"))
    path.mkdir(parents=True, exist_ok=True)
    return path


def synthetic_anticausal_tail(n_terms: int) -> np.ndarray:
    """Return a stable finite-rank anticausal tail.

    A sum of damped exponentials has finite Hankel rank in exact arithmetic.  It
    is therefore a clean teaching object for the bridge from Hankel matrices to
    rational/recursive models.
    """

    n = np.arange(n_terms, dtype=float)
    poles = np.array([0.91, 0.66, -0.43, 0.22], dtype=float)
    weights = np.array([1.00, 0.28, -0.15, 0.045], dtype=float)
    return np.sum(weights[:, None] * poles[:, None] ** n[None, :], axis=0)


def fit_rational_tail(tail: np.ndarray, order: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Fit a scalar recurrence/IIR model to a tail sequence.

    For a sequence ``g[n]`` generated by a stable rational model, there are
    coefficients ``a_1, ..., a_p`` such that

        g[n] + a_1 g[n-1] + ... + a_p g[n-p] = 0.

    The denominator ``[1, a_1, ..., a_p]`` is estimated by least squares.  The
    numerator is then chosen so that the first ``p+1`` impulse samples match the
    supplied tail.
    """

    tail = np.asarray(tail, dtype=float)
    if tail.ndim != 1:
        raise ValueError("tail must be one-dimensional")
    if order < 0:
        raise ValueError("order must be non-negative")
    if order == 0:
        return np.array([1.0]), np.array([float(tail[0])]), np.array([], dtype=float)
    if tail.size < 2 * order + 1:
        raise ValueError("tail is too short for the requested rational order")

    x = []
    y = []
    for n in range(order, tail.size):
        x.append([tail[n - lag] for lag in range(1, order + 1)])
        y.append(-tail[n])
    x_arr = np.asarray(x, dtype=float)
    y_arr = np.asarray(y, dtype=float)
    coeff, *_ = np.linalg.lstsq(x_arr, y_arr, rcond=None)
    denominator = np.concatenate(([1.0], coeff))

    numerator = np.zeros(order + 1, dtype=float)
    for i in range(order + 1):
        numerator[i] = sum(denominator[j] * tail[i - j] for j in range(i + 1))

    poles = np.roots(denominator)
    return denominator, numerator, poles


def rational_tail_response(
    denominator: np.ndarray, numerator: np.ndarray, n_terms: int
) -> np.ndarray:
    """Generate an impulse/tail sequence from scalar IIR coefficients."""

    denominator = np.asarray(denominator, dtype=float)
    numerator = np.asarray(numerator, dtype=float)
    if denominator.ndim != 1 or numerator.ndim != 1:
        raise ValueError("denominator and numerator must be one-dimensional")
    if denominator.size == 0 or abs(float(denominator[0])) < 1e-15:
        raise ValueError("denominator[0] must be non-zero")

    a = denominator / denominator[0]
    b = numerator / denominator[0]
    y = np.zeros(n_terms, dtype=float)
    for n in range(n_terms):
        value = b[n] if n < b.size else 0.0
        for k in range(1, a.size):
            if n >= k:
                value -= a[k] * y[n - k]
        y[n] = value
    return y


def relative_error(reference: np.ndarray, estimate: np.ndarray) -> float:
    num = float(np.linalg.norm(reference - estimate))
    den = float(np.linalg.norm(reference))
    return num / den if den else 0.0


def write_summary(path: Path, rows: list[dict[str, float | int]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    import lattice_dsp as ld

    out_dir = artifact_dir()

    rows = cols = 48
    tail = synthetic_anticausal_tail(rows + cols - 1)
    ranks = [2, 3, 4]

    summary: list[dict[str, float | int]] = []
    approximations: dict[int, np.ndarray] = {}
    rational_responses: dict[int, np.ndarray] = {}
    fitted_poles: dict[int, np.ndarray] = {}
    singular_values: np.ndarray | None = None

    for rank in ranks:
        nehari = ld.finite_nehari_approximate_tail(tail.tolist(), rank=rank, rows=rows, cols=cols)
        if singular_values is None:
            singular_values = np.asarray(nehari["hankel_singular_values"], dtype=float)

        approx_tail = np.asarray(nehari["approximated_tail"], dtype=float)
        denominator, numerator, poles = fit_rational_tail(approx_tail, rank)
        rational = rational_tail_response(denominator, numerator, tail.size)

        approximations[rank] = approx_tail
        rational_responses[rank] = rational
        fitted_poles[rank] = poles

        summary.append(
            {
                "rank": rank,
                "sigma_next": float(nehari["sigma_next"]),
                "finite_nehari_tail_relative_error": float(nehari["relative_tail_error"]),
                "rational_vs_original_relative_error": relative_error(tail, rational),
                "rational_vs_hankelized_relative_error": relative_error(approx_tail, rational),
                "max_pole_radius": float(np.max(np.abs(poles))) if poles.size else 0.0,
            }
        )

    assert singular_values is not None

    csv_path = out_dir / "finite_nehari_rational_bridge_summary.csv"
    write_summary(csv_path, summary)

    print("finite Hankel matrix:", f"{rows} x {cols}")
    print("leading singular values:", [round(float(v), 6) for v in singular_values[:8]])
    for row in summary:
        print(
            "rank={rank}: sigma_next={sigma_next:.3e}, tail_error={finite_nehari_tail_relative_error:.3e}, "
            "rational_error={rational_vs_original_relative_error:.3e}, pole_radius={max_pole_radius:.4f}".format(
                **row
            )
        )
    print(f"wrote {csv_path}")

    try:
        import matplotlib.pyplot as plt
    except Exception:
        print("matplotlib is not installed; skipped figures")
        return

    fig, ax = plt.subplots(figsize=(8.5, 4.5))
    idx = np.arange(1, 21)
    ax.semilogy(idx, singular_values[:20], marker="o")
    ax.set_title("Hankel singular values of the anticausal tail")
    ax.set_xlabel("index")
    ax.set_ylabel("singular value")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    path = out_dir / "finite_nehari_rational_bridge_singular_values.png"
    fig.savefig(path, dpi=160)
    print(f"wrote {path}")

    fig2, ax2 = plt.subplots(figsize=(9.0, 4.8))
    n = np.arange(1, 41)
    ax2.plot(n, tail[:40], linewidth=2.0, label="target tail")
    for rank in ranks:
        ax2.plot(n, approximations[rank][:40], "--", linewidth=1.2, label=f"rank {rank} Hankelized")
        ax2.plot(
            n, rational_responses[rank][:40], ":", linewidth=1.4, label=f"rank {rank} rational"
        )
    ax2.set_title("Finite Nehari tail approximation and rational realization")
    ax2.set_xlabel("tail coefficient index")
    ax2.set_ylabel("coefficient value")
    ax2.grid(True, alpha=0.3)
    ax2.legend(ncol=2, fontsize=8)
    fig2.tight_layout()
    path2 = out_dir / "finite_nehari_rational_bridge_tail_fit.png"
    fig2.savefig(path2, dpi=160)
    print(f"wrote {path2}")

    fig3, ax3 = plt.subplots(figsize=(5.6, 5.6))
    theta = np.linspace(0.0, 2.0 * math.pi, 512)
    ax3.plot(np.cos(theta), np.sin(theta), "--", linewidth=1.0, label="unit circle")
    for rank, poles in fitted_poles.items():
        ax3.scatter(np.real(poles), np.imag(poles), label=f"rank {rank} poles")
    ax3.axhline(0.0, linewidth=0.8)
    ax3.axvline(0.0, linewidth=0.8)
    ax3.set_aspect("equal", adjustable="box")
    ax3.set_title("Poles of the fitted rational tail models")
    ax3.set_xlabel("real")
    ax3.set_ylabel("imaginary")
    ax3.grid(True, alpha=0.3)
    ax3.legend(fontsize=8)
    fig3.tight_layout()
    path3 = out_dir / "finite_nehari_rational_bridge_poles.png"
    fig3.savefig(path3, dpi=160)
    print(f"wrote {path3}")


if __name__ == "__main__":
    main()
